# Generated by Django 5.0.1 on 2024-03-04 04:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanditJi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=72),
            preserve_default=False,
        ),
    ]
