# Generated by Django 5.0.1 on 2024-03-31 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PanditJi', '0003_panditprofiledata_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='serviceData',
        ),
    ]
