# Generated by Django 5.0.1 on 2024-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanditJi', '0005_rename_experienc_panditprofiledata_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panditprofiledata',
            name='city',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='country',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='experience',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='faddress',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='gender',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='high_edu',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='lang',
            field=models.TextField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='photo',
            field=models.ImageField(blank=True, max_length=2048, upload_to='userImages/'),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='pincode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='pname',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='skill',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='state',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='supp_docs',
            field=models.FileField(blank=True, max_length=2048, upload_to='userImages/'),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='whatsapp',
            field=models.IntegerField(blank=True),
        ),
    ]
