# Generated by Django 5.0.1 on 2024-05-15 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanditJi', '0006_alter_panditprofiledata_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panditprofiledata',
            name='experience',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='photo',
            field=models.ImageField(default='userImages/profile.png', max_length=2048, upload_to='userImages/'),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='pincode',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='supp_docs',
            field=models.FileField(default='userImages/profile.png', max_length=2048, upload_to='userImages/'),
        ),
        migrations.AlterField(
            model_name='panditprofiledata',
            name='whatsapp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.IntegerField()),
                ('ritual_date', models.DateField()),
                ('ritual_time', models.TimeField()),
                ('destination', models.TextField(max_length=255)),
                ('additional', models.TextField(blank=True, default=None, max_length=500)),
                ('charge', models.IntegerField()),
                ('N_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PanditJi.people')),
                ('P_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PanditJi.pandit')),
                ('ritual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PanditJi.servicedata')),
            ],
        ),
    ]
