# Generated by Django 5.0.1 on 2024-05-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanditJi', '0007_alter_panditprofiledata_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
