# Generated by Django 5.0.1 on 2024-05-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanditJi', '0008_bookings_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='ritual_name',
            field=models.TextField(default='Bhumi Poojan', max_length=255),
        ),
    ]
