# Generated by Django 5.0.1 on 2024-05-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanditJi', '0009_bookings_ritual_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='ritual_name',
            field=models.TextField(max_length=255),
        ),
    ]
